### ISSUE TITLE
Act like cron?

### ISSUE THREAD

**Issue by klabacita** [jacobdjwilson/pfMailReport#3]
Hello, excellent piece of software, thanks.
I would like to know if mailreport can act like cron went we setup the time to run the task?
With cron we can schedule to run our task every minute, 3 minutes, 15 minutes etc etc.
This can let us track some behavior with my system.
U think would be a good feature?
Regards!!!

**Comment by jacobdjwilson** [comment]
Thank you for the kind words, I'm glad it's helping the community.

pfMailReport can be incorporated into cron jobs. Simply run the commands via **Services > Cron** and output to a location like /tmp and subsequently cat the results into the **Status > Email Reports**. I have an example of this in [commands/speedtest_full.sh](https://github.com/jacobdjwilson/pfMailReport/blob/471652e60376ea24aa6de24f130583a55cc6b853/commands/speedtest_full.sh)

Of course the next logical step in this progression is tracking of data over time, which would lead us to solutions like databases or log rotation tools. I have instead utilized the built-in functions of the utilities which the example commands come from in order to track data over time. One example of this is [commands/traffic_totals.sh](https://github.com/jacobdjwilson/pfMailReport/blob/471652e60376ea24aa6de24f130583a55cc6b853/commands/traffic_totals.sh) where you can change the option flag of vnstat **-d** to **-h** to display traffic counts hourly rather than daily.

And the next step of tracking data over time is to visually display the data in a meaningful chart or graph. Which I have been working toward completing in the development branch of code in [commands/traffic_totals_graph.sh](https://github.com/jacobdjwilson/pfMailReport/blob/e977b48f7fe3cd99656815582ceed25172c6b900/commands/traffic_totals_graph.sh) along with other features such as rich email templates.

Please have a look into the development branch for more insights, and feel free to contribute back if you have success with scheduled jobs or graphing. We're always looking for new techniques.

**Comment by klabacita** [comment]
Excellent work, I have test your reports and looks good.
The idea is to use cron+mailreport and we have a Swiss knife.
I will watch your progress and see how can I contribute.
Thanks again!!!
